### ISSUE TITLE
Refuses to compile on CygWin 2.7.0 with g++

### ISSUE THREAD

**Issue by evgfilim1** [UjGamer/scet#2] opened 2017-02-21 14:34 UTC
### More info:
Packages that were used to provide GCC on CygWin: `gcc-core`, `gcc-g++`
```bash
$ g++ --version
g++ (GCC) 5.4.0
...
```

**Comment by OctoNezd** [comment] 2017-02-21 15:47
@evgfilim1 уууу евген перешел на винду

**Comment by UjGamer** [comment] 2017-02-23 15:51
Sorry, can't reproduce because Cygwin doesn't works for me for some reason.
Please, provide full error message you getting when trying to execute `cmake` or `make`.

**Comment by evgfilim1** [comment] 2017-02-27 04:59
@UjGamer here is full compile log [on pastebin](http://pastebin.com/XcpRjzex)

**Comment by UjGamer** [comment] 2017-02-27 17:34
Try to compile with this patch.
[0001-ISSUE-2.patch.txt](https://github.com/UjGamer/scet/files/804453/0001-ISSUE-2.patch.txt)

**Comment by UjGamer** [comment] 2017-02-27 17:49
@evgfilim1, try to compile with this patch.
1. `cd` into repository directory.
2. Run `git apply 0001-ISSUE-2....txt`

[0001-ISSUE-2-Provide-trivial-implementation-for-some-opti.patch.txt](https://github.com/UjGamer/scet/files/804494/0001-ISSUE-2-Provide-trivial-implementation-for-some-opti.patch.txt)

**Comment by UjGamer** [comment] 2017-03-02 13:19
Fixed in 40b2610881f139d10e1d573b13aa0a2ee01c3169. If still not compiling - reopen.

**Closed by UjGamer** 2017-03-02 13:19 UTC
